### ISSUE TITLE
Error with user access to fund codes

### ISSUE THREAD

**Issue by kingstonrichard** [LocalGovIMS/localgov-ims#29]
transaction list screen showing transfer record because user has access to fund code, but when selecting to view details it bombs because the original transaction is to a fund code that the user does not have access to

**Comment by bmbc-dev-detec** [comment]
The initial description of the error is wrong.

'it bombs because the original transaction is to a fund code that the user does not have access to' is incorrcet.

It 'bombs' because if a user is viewing a transfer (or journal) transaction, and they only have access to one half of it, there is some logic in the TransactionService to return null, instead of the transaction.

I've discussed this with @zoecrosby and we can't think of a reason for it, so removing this logic will give users access to the details page.

That resolves the specific issue that was initially noted: 'transaction list screen showing transfer record because user has access to fund code, but when selecting to view details it bombs'

**Comment by bmbc-dev-detec** [comment]
Completed
